services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  airflow-webserver:
    build: .
    image: agri-airflow:2.9.0
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECURE_COOKIES_IN_BROWSER_ONLY: 'false'
      AIRFLOW__WEBSERVER__COOKIE_SECURE: 'false'
      AIRFLOW__WEBSERVER__COOKIE_SAMESITE: 'Lax'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
      AIRFLOW__WEBSERVER__RBAC: 'true'
      AIRFLOW__WEBSERVER__EXPOSE_STACKTRACE: 'true'
      AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL: '60'
      AIRFLOW__WEBSERVER__BASE_LOG_FOLDER: '/opt/airflow/logs'
      AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: 'true'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    image: agri-airflow:2.9.0
    depends_on:
      - airflow-webserver
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECURE_COOKIES_IN_BROWSER_ONLY: 'false'
      AIRFLOW__WEBSERVER__COOKIE_SECURE: 'false'
      AIRFLOW__WEBSERVER__COOKIE_SAMESITE: 'Lax'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    command: scheduler